config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :workouts do

    collection do
        get 'mileage_chart'
        get 'training_suggestion'
    end

  end

  root to: "workouts#index"

end

app/models/training_partner.rb
# logic for workouts will be calculated here

class TrainingPartner

  # need to get previous 2 weeks mileage
  # also need to get rolling 7 day mileage (sort of)

  # pass in user workouts
  def initialize(user:)

    @workouts = user.workouts.group_by_week(:date).sum(:distance)
    # inputs
    @rolling_total = user.rolling_7_day_mileage
    @last_week_total = user.get_previous_week_mileage(weeks_ago: 1)
    @current_week_total = user.get_previous_week_mileage(weeks_ago: 0)
    # I should account for their being more than one run entered on a given day
    # @yesterday_distance = user.workouts.group(:date).order("date DESC").sum(:distance)&.first[1]
    @last_hard_day = user.workouts.where(:effort => Workout::EFFORT_LIST.last).order("date DESC").take&.date

  end


  def suggest_run
    # Rules
    # - Want to keep rolling mileage under last week total * 1.1
    # - Want to keep week to week increase under 10%
    # - Hard / Workouts should be followed by a recovery day
    # - Need to make sure we have room in current week mileage for the above long run + a short recovery run the following day
    # - Need some formula to calc what a long run should be - Maybe avg total mileage / 4 ?

    # inputs - rolling total - current week total - last week total - yesterdays run

    # Might be a good candidate for a rules engine but for now keep it simple

    # if yesterday was a hard day return an easy 1.5-3 mile run - figure out the scaling based on last week total
    if @last_hard_day == Date.yesterday
      easy_run = @last_week_total / 10
      return "Easy #{ easy_run <= 1.5 ? 1.5 : easy_run } mile run to recover from yesterdays hard effort"
    # if there is room for a long run recommend it
    elsif room_in_rolling_total? && room_in_current_week?
      return "Moderate #{long_run_distance} mile long run"
    else
      return 42
    end

  end

  # should probably get an average total mileage of the last few weeks for better accuracy
  def long_run_distance
    @last_week_total / 4.0
  end

  # determine if there is room for long run in current rolling total mileage
  def room_in_rolling_total?
    (@rolling_total + long_run_distance) < (@last_week_total * 1.1)
  end

  # check daily average vs expected (with margin)
  def room_in_current_week?
    ((@current_week_total / Date.today.cwday) / 0.9 ) < ( (@last_week_total * 1.1) / 7.0)
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :workouts

  def rolling_7_day_mileage
    self.workouts.where(:date => 7.days.ago.beginning_of_day..DateTime.now.end_of_day ).sum(:distance)
  end

  # def last_weeks_mileage
  #   self.workouts.where(:date => 1.week.ago.beginning_of_week..1.week.ago.end_of_week).sum(:distance)
  # end

  def get_previous_week_mileage(weeks_ago: )
    self.workouts.where(:date => weeks_ago.week.ago.beginning_of_week..weeks_ago.week.ago.end_of_week).sum(:distance)
  end

end

app/models/workout.rb
class Workout < ActiveRecord::Base
  belongs_to :user

  validates :date, presence: true
  validates :distance, presence: true, numericality: true
  validates :effort, presence: true

  validate :date_valid?

  EFFORT_LIST = ['easy / recovery', 'moderate', 'difficult / workout']

  def date_valid?
    errors.add(:date, "should be in the following format: mm/dd/yyyy") unless date.present? && date.is_a?(ActiveSupport::TimeWithZone)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  def index
    @workouts = current_user.workouts
    @rolling_total = current_user.rolling_7_day_mileage
    #@last_week_total = current_user.last_weeks_mileage
    @last_week_total = current_user.get_previous_week_mileage(weeks_ago: 1)

    # final plan would be do an ajax get for the run suggestion so we're doing doing the setup calculations if we need to
    # and display it in some sort of pop up dialog
    @suggested_run = training_suggestion
  end

  def new
    @workout = current_user.workouts.build
  end

  def edit
    @workout = current_user.workouts.find(params[:id])
  end

  def create
    @workout = current_user.workouts.build(workout_params)

    if @workout.save
      redirect_to workouts_path(current_user)
    else
      render 'new'
    end

  end

  def update
    @workout = current_user.workouts.find(params[:id])

    if @workout.update(workout_params)
      redirect_to workouts_path(current_user)
    else
      render 'edit'
    end

  end

  # some kind of modal jquery pop up maybe ?
  def training_suggestion
    TrainingPartner.new(user: current_user).suggest_run
  end

  def mileage_chart
    render json: current_user.workouts.group_by_week(:date).sum(:distance)
  end

  private

  def workout_params
    params.require(:workout).permit(:date,:distance,:effort,:note)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://www.google.com/jsapi" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/workouts/_form.html.erb
<%= form_for(@workout) do |f| %>

<% if @workout.errors.any? %>

  <div id="error_explanation">
   <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this run from being saved:</h2>

   <ul>
     <% @workout.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
  </div>

<% end %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :distance %>
  <%= f.number_field :distance, :step => ".01" %>

  <%= f.label :effort %>
  <%= f.select :effort, Workout::EFFORT_LIST, :include_blank => true %>

  <%= f.label :note %>
  <%= f.text_field :note %>

<%= f.submit @workout.new_record? ? "Submit" : "Update" %>

<% end %>

app/views/workouts/edit.html.erb
<h1>Workout#edit</h1>

<%= render :partial => 'form', locals: {workout: @workout} %>

app/views/workouts/index.html.erb
<h1>Workout#index</h1>
<p>Find me in app/views/workout/index.html.erb</p>

<p> Hello <%= current_user.email %> </p>

<%= link_to "Log New Run", new_workout_path(current_user), class: "button" %>
Training Suggestion: <%= @suggested_run %>

<p> List view workout data for now. Would like to graph things though</p>

<p> Rolling 7 day total mileage:  <%= number_with_precision(@rolling_total , precision: 1) %> </p>
<p> Last weeks total mileage: <%= number_with_precision(@last_week_total, precision: 1) %> </p>

<%= line_chart mileage_chart_workouts_path %>

<table id="run-index-table">
  <caption>Table of logged runs</caption>
  <thead>
    <tr>
      <th>Date</th>
      <th>Distance</th>
      <th>Effort</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <% @workouts.each do |run| %>
      <tr data-link="<%= edit_workout_path(run.id) %>">
        <td><%= run.date.strftime('%m/%d/%Y') %></td>
        <td><%= run.distance %></td>
        <td><%= run.effort %></td>
        <td><%= truncate(run.note, length: 60) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workouts/new.html.erb
<h1>Workout#new</h1>

<%= form_for(@workout) do |f| %>

<% if @workout.errors.any? %>

  <div id="error_explanation">
   <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this run from being saved:</h2>

   <ul>
     <% @workout.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
   </ul>
  </div>

<% end %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :distance %>
  <%= f.number_field :distance, :step => ".01" %>

  <%= f.label :effort %>
  <%= f.select :effort, Workout::EFFORT_LIST, :include_blank => true %>

  <%= f.label :note %>
  <%= f.text_field :note %>

<%= f.submit %>

<% end %>